version: '3'

services:
  deploy:
    image: nginx:1.13.9-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./remove:/var/log/nginx
    ports:
      - '4202:80'
    extra_hosts:
      - "host.docker.internal:host-gateway"
