FROM node:10.16.3 AS build-env

WORKDIR /app

COPY . ./

ARG ENVIRONMENT

RUN npm install
RUN if [ "$ENVIRONMENT" = "dev" ] ; then npm run build:admin ; else npm run build:admin:prod ; fi

FROM nginx:1.13.9-alpine

COPY --from=build-env /app/dist/admin/ /usr/share/nginx/html

COPY ./nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
